
#include "ft_printf.h"

int		main(int ac, char **av)
{
	ft_printf("%a", (double)42);
	ft_printf("Kashim a %a histoires à raconter", (double)1001);
	ft_printf("Il fait au moins %a\n", (double)-8000);
	ft_printf("%a", (double)-0);
	ft_printf("%a", (double)0);
	ft_printf("%a", (double)INT_MAX);
	ft_printf("%a", (double)INT_MIN);
	ft_printf("%a", (double)INT_MIN - 1);
	ft_printf("%a", (double)INT_MAX + 1);
	ft_printf("%%a 0000042 == |%a|\n", (double)0000042);
	ft_printf("%%a \t == |%a|\n", (double)'\t');
	ft_printf("%%a Lydie == |%a|\n", (double)'L'+'y'+'d'+'i'+'e');
	ft_printf("%%a 42.42 == |%a|\n", 42.42);
	ft_printf("%A", (double)42);
	ft_printf("Kashim a %A histoires à raconter", (double)1001);
	ft_printf("Il fait au moins %A\n", (double)-8000);
	ft_printf("%A", (double)-0);
	ft_printf("%A", (double)0);
	ft_printf("%A", (double)INT_MAX);
	ft_printf("%A", (double)INT_MIN);
	ft_printf("%A", (double)INT_MIN - 1);
	ft_printf("%A", (double)INT_MAX + 1);
	ft_printf("%%A 0000042 == |%A|\n", (double)0000042);
	ft_printf("%%A \t == |%A|\n", (double)'\t');
	ft_printf("%%A Lydie == |%A|\n", (double)'L'+'y'+'d'+'i'+'e');
	ft_printf("%%A 42.42 == |%A|\n", 42.42);
	ft_printf("%%A 42.42 == |%.2A|\n", 42.42);
	ft_printf("%c", 42);
	ft_printf("Kashim a %c histoires à raconter", 1001);
	ft_printf("Il fait au moins %c\n", -8000);
	ft_printf("%c", -0);
	ft_printf("%c", 0);
	ft_printf("%c\n", INT_MAX);
	ft_printf("%c\n", 'c');
	ft_printf("%c\n", '\n');
	ft_printf("%c", 'l');
	ft_printf("%c", 'y');
	ft_printf("%c", ' ');
	ft_printf("%c", 'e');
	ft_printf("%c", 's');
	ft_printf("%c", 't');
	ft_printf("%c", ' ');
	ft_printf("%c", 'f');
	ft_printf("%c", 'a');
	ft_printf("%c", 'n');
	ft_printf("%c", 't');
	ft_printf("%c", 'a');
	ft_printf("%c", 's');
	ft_printf("%c", 't');
	ft_printf("%c", 'i');
	ft_printf("%c", 'q');
	ft_printf("%c", 'u');
	ft_printf("%c", 'e');
	ft_printf("%c\n", '!');
	ft_printf("%c\n", '\r');
	ft_printf("%c\n", '\t');
	ft_printf("%d", 42);
	ft_printf("Kashim a %d histoires à raconter", 1001);
	ft_printf("Il fait au moins %d\n", -8000);
	ft_printf("%d", -0);
	ft_printf("%d", 0);
	ft_printf("%d", INT_MAX);
	ft_printf("%d", INT_MIN);
	ft_printf("%d", INT_MIN - 1);
	ft_printf("%d", INT_MAX + 1);
	ft_printf("%%d 0000042 == |%d|\n", 0000042);
	ft_printf("%%d \t == |%d|\n", '\t');
	ft_printf("%%d Lydie == |%d|\n", 'L'+'y'+'d'+'i'+'e');
	ft_printf("%e", (double)42);
	ft_printf("Kashim a %e histoires à raconter", (double)1001);
	ft_printf("Il fait au moins %e\n", (double)-8000);
	ft_printf("%e", (double)-0);
	ft_printf("%e", (double)0);
	ft_printf("%e", (double)INT_MAX);
	ft_printf("%e", (double)INT_MIN);
	ft_printf("%e", (double)INT_MIN - 1);
	ft_printf("%e", (double)INT_MAX + 1);
	ft_printf("%%e 0000042 == |%e|\n", (double)0000042);
	ft_printf("%%e \t == |%e|\n", (double)'\t');
	ft_printf("%%e Lydie == |%e|\n", (double)'L'+'y'+'d'+'i'+'e');
	ft_printf("%%e 42.42 == |%e|\n", 42.42);
	ft_printf("%E", (double)42);
	ft_printf("Kashim a %E histoires à raconter", (double)1001);
	ft_printf("Il fait au moins %E\n", (double)-8000);
	ft_printf("%E", (double)-0);
	ft_printf("%E", (double)0);
	ft_printf("%E", (double)INT_MAX);
	ft_printf("%E", (double)INT_MIN);
	ft_printf("%E", (double)INT_MIN - 1);
	ft_printf("%E", (double)INT_MAX + 1);
	ft_printf("%%E 0000042 == |%E|\n", (double)0000042);
	ft_printf("%%E \t == |%E|\n", (double)'\t');
	ft_printf("%%E Lydie == |%E|\n", (double)'L'+'y'+'d'+'i'+'e');
	ft_printf("%%E 42.42 == |%E|\n", 42.42);
	ft_printf("%%E 42.42 == |%.2E|\n", 42.42);
	ft_printf("%f", (double)42);
	ft_printf("Kashim a %f histoires à raconter", (double)1001);
	ft_printf("Il fait au moins %f\n", (double)-8000);
	ft_printf("%f", (double)-0);
	ft_printf("%f", (double)0);
	ft_printf("%f", (double)INT_MAX);
	ft_printf("%f", (double)INT_MIN);
	ft_printf("%f", (double)INT_MIN - 1);
	ft_printf("%f", (double)INT_MAX + 1);
	ft_printf("%%f 0000042 == |%f|\n", (double)0000042);
	ft_printf("%%f \t == |%f|\n", (double)'\t');
	ft_printf("%%f Lydie == |%f|\n", (double)'L'+'y'+'d'+'i'+'e');
	ft_printf("%%f 42.42 == |%f|\n", 42.42);
	ft_printf("%F", (double)42);
	ft_printf("Kashim a %F histoires à raconter", (double)1001);
	ft_printf("Il fait au moins %F\n", (double)-8000);
	ft_printf("%F", (double)-0);
	ft_printf("%F", (double)0);
	ft_printf("%F", (double)INT_MAX);
	ft_printf("%F", (double)INT_MIN);
	ft_printf("%F", (double)INT_MIN - 1);
	ft_printf("%F", (double)INT_MAX + 1);
	ft_printf("%%F 0000042 == |%F|\n", (double)0000042);
	ft_printf("%%F \t == |%F|\n", (double)'\t');
	ft_printf("%%F Lydie == |%F|\n", (double)'L'+'y'+'d'+'i'+'e');
	ft_printf("%%F 42.42 == |%F|\n", 42.42);
	ft_printf("%%F 42.42 == |%.2F|\n", 42.42);
	ft_printf("%g", (double)42);
	ft_printf("Kashim a %g histoires à raconter", (double)1001);
	ft_printf("Il fait au moins %g\n", (double)-8000);
	ft_printf("%g", (double)-0);
	ft_printf("%g", (double)0);
	ft_printf("%g", (double)INT_MAX);
	ft_printf("%g", (double)INT_MIN);
	ft_printf("%g", (double)INT_MIN - 1);
	ft_printf("%g", (double)INT_MAX + 1);
	ft_printf("%%g 0000042 == |%g|\n", (double)0000042);
	ft_printf("%%g \t == |%g|\n", (double)'\t');
	ft_printf("%%g Lydie == |%g|\n", (double)'L'+'y'+'d'+'i'+'e');
	ft_printf("%%g 42.42 == |%g|\n", 42.42);
	ft_printf("%G", (double)42);
	ft_printf("Kashim a %G histoires à raconter", (double)1001);
	ft_printf("Il fait au moins %G\n", (double)-8000);
	ft_printf("%G", (double)-0);
	ft_printf("%G", (double)0);
	ft_printf("%G", (double)INT_MAX);
	ft_printf("%G", (double)INT_MIN);
	ft_printf("%G", (double)INT_MIN - 1);
	ft_printf("%G", (double)INT_MAX + 1);
	ft_printf("%%G 0000042 == |%G|\n", (double)0000042);
	ft_printf("%%G \t == |%G|\n", (double)'\t');
	ft_printf("%%G Lydie == |%G|\n", (double)'L'+'y'+'d'+'i'+'e');
	ft_printf("%%G 42.42 == |%G|\n", 42.42);
	ft_printf("%%G 42.42 == |%.2G|\n", 42.42);
	ft_printf("%i", 42);
	ft_printf("Kashim a %i histoires à raconter", 1001);
	ft_printf("Il fait au moins %i\n", -8000);
	ft_printf("%i", -0);
	ft_printf("%i", 0);
	ft_printf("%i", INT_MAX);
	ft_printf("%i", INT_MIN);
	ft_printf("%i", INT_MIN - 1);
	ft_printf("%i", INT_MAX + 1);
	ft_printf("%%i 0000042 == |%i|\n", 0000042);
	ft_printf("%%i \t == |%i|\n", '\t');
	ft_printf("%%i Lydie == |%i|\n", 'L'+'y'+'d'+'i'+'e');
	ft_printf("%Le", (long double)42);
	ft_printf("Kashim a %Le histoires à raconter", (long double)1001);
	ft_printf("Il fait au moins %Le\n", (long double)-8000);
	ft_printf("%Le", (long double)-0);
	ft_printf("%Le", (long double)0);
	ft_printf("%Le", (long double)INT_MAX);
	ft_printf("%Le", (long double)INT_MIN);
	ft_printf("%Le", (long double)INT_MIN - 1);
	ft_printf("%Le", (long double)INT_MAX + 1);
	ft_printf("%Le", (long double)LONG_MAX);
	ft_printf("%Le", (long double)LONG_MIN);
	ft_printf("%Le", (long double)LONG_MIN - 1);
	ft_printf("%Le", (long double)LONG_MAX + 1);
	ft_printf("%%Le 0000042 == |%Le|\n", (long double)0000042);
	ft_printf("%%Le \t == |%Le|\n", (long double)'\t');
	ft_printf("%%Le Lydie == |%Le|\n", (long double)'L'+'y'+'d'+'i'+'e');
	ft_printf("%%Le 42.42 == |%Le|\n", (long double)42.42);
	ft_printf("%C\n", L'ø');
	ft_printf("%D", 42);
	ft_printf("Kashim a %D histoires à raconter", 1001);
	ft_printf("Il fait au moins %D\n", -8000);
	ft_printf("%D", -0);
	ft_printf("%D", 0);
	ft_printf("%D", INT_MAX);
	ft_printf("%D", INT_MIN);
	ft_printf("%D", INT_MIN - 1);
	ft_printf("%D", INT_MAX + 1);
	ft_printf("%%D 0000042 == |%D|\n", 0000042);
	ft_printf("%%D \t == |%D|\n", '\t');
	ft_printf("%%D Lydie == |%D|\n", 'L'+'y'+'d'+'i'+'e');
	ft_printf("%%-d 42 == %-d\n", INT_MIN);
	ft_printf("%%-i -42 == %-i\n", -42);
	ft_printf("%%-4d 42 == |%-4d|\n", 42);
	ft_printf("%%-5d -42 == |%-5d|\n", -42);
	ft_printf("|%3i|%-3i|\n", 42, 42);
	ft_printf("%%-4i 42 == |%-4i|\n", 42);
	ft_printf("%o", 42);
	ft_printf("Kashim a %o histoires à raconter", 1001);
	ft_printf("Il fait au moins %o\n", -8000);
	ft_printf("%o", -0);
	ft_printf("%o", 0);
	ft_printf("%o", INT_MAX);
	ft_printf("%o", INT_MIN);
	ft_printf("%o", INT_MIN - 1);
	ft_printf("%o", INT_MAX + 1);
	ft_printf("%%o 0000042 == |%o|\n", 0000042);
	ft_printf("%%o \t == |%o|\n", '\t');
	ft_printf("%%o Lydie == |%o|\n", 'L'+'y'+'d'+'i'+'e');
	ft_printf("%%+i 42 == %+i\n", 42);
	ft_printf("%%+d 42 == %+d\n", INT_MAX);
	ft_printf("%%+i -42 == %+i\n", -42);
	ft_printf("%%+04d 42 == %0+04d\n", 42);
	ft_printf("%%-5.3s LYDI == |%-5.3s|\n", "LYDI");
	ft_printf("%% 4.5i 42 == |% 4.5i|\n", 42);
	ft_printf("%%04.5i 42 == |%04.5i|\n", 42);
	ft_printf("%%04.3i 42 == |%04.3i|\n", 42);
	ft_printf("%%04.2i 42 == |%04.2i|\n", 42);
	ft_printf("%s", "pouet");
	ft_printf(" pouet %s !!\n", "camembert");
	ft_printf("%s !\n", "Ceci n'est pas un \0 exercice !");
	ft_printf("%s!\n", "Ceci n'est toujours pas un exercice !");
	ft_printf("%s", "Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Etalafinilla*bip*");
	ft_printf("%%#X 42 ==  %#X\n", 42);
	ft_printf("%%X 42 ==  %X\n", 42);
	ft_printf("%%#o 0 ==  %#o\n", 0);
	ft_printf("%%o 0 ==  %o\n", 0);
	ft_printf("%%#o INT_MAX ==  %#o\n", INT_MAX);
	ft_printf("%%o INT_MAX ==  %o\n", INT_MAX);
	ft_printf("%%#o INT_MIN ==  %#o\n", INT_MIN);
	ft_printf("%%o INT_MIN ==  %o\n", INT_MIN);
	ft_printf("%%#X INT_MIN ==  %#X\n", INT_MIN);
	ft_printf("%%X INT_MIN ==  %X\n", INT_MIN);
	ft_printf("%%#X INT_MAX ==  %#X\n", INT_MAX);
	ft_printf("%%X INT_MAX ==  %X\n", INT_MAX);
	ft_printf("%%      i 42 == |%      i|\n", 42);
	ft_printf("%% i -42 == |% i|\n", -42);
	ft_printf("%% 4i 42 == |% 4i|\n", 42);
	ft_printf("%%-*.3s LYDI == |%-*.3s|\n", 5, "LYDI");
	ft_printf("%% *.5i 42 == |% *.5i|\n", 4, 42);
	ft_printf("%%*i 42 == |%*i|\n", 5, 42);
	ft_printf("%%*i 42 == |%*i|\n", 3, 42);
	ft_printf("%%*i 42 == |%*i|\n", 2, 42);
	ft_printf("%u", 42);
	ft_printf("Kashim a %u histoires à raconter", 1001);
	ft_printf("Il fait au moins %u\n", -8000);
	ft_printf("%u", -0);
	ft_printf("%u", 0);
	ft_printf("%u", INT_MAX);
	ft_printf("%u", INT_MIN);
	ft_printf("%u", INT_MIN - 1);
	ft_printf("%u", INT_MAX + 1);
	ft_printf("%%u 0000042 == |%u|\n", 0000042);
	ft_printf("%%u \t == |%u|\n", '\t');
	ft_printf("%%u Lydie == |%u|\n", 'L'+'y'+'d'+'i'+'e');
	ft_printf("%x", 42);
	ft_printf("Kashim a %x histoires à raconter", 1001);
	ft_printf("Il fait au moins %x\n", -8000);
	ft_printf("%x", -0);
	ft_printf("%x", 0);
	ft_printf("%x", INT_MAX);
	ft_printf("%x", INT_MIN);
	ft_printf("%x", INT_MIN - 1);
	ft_printf("%x", INT_MAX + 1);
	ft_printf("%%x 0000042 == |%x|\n", 0000042);
	ft_printf("%%x \t == |%x|\n", '\t');
	ft_printf("%%x Lydie == |%x|\n", 'L'+'y'+'d'+'i'+'e');
	ft_printf("%%04i 42 == |%04i|\n", 42);
	ft_printf("%%05i 42 == |%05i|\n", 42);
	ft_printf("%%0i 42 == |%0i|\n", 42);
	ft_printf("%%0d 0000042 == |%0d|\n", 0000042);
	return (0);
}
